"""Public deterministic Rule interfaces and bounded Phase 1 matchers."""

from agentsec.rules.base import (
    Rule,
    RuleContext,
    RuleContractError,
    RuleEvaluation,
    RuleEvaluationError,
    RuleEvidenceCandidate,
    RuleFindingCandidate,
    RuleMetadata,
    RuleScope,
    RuleTarget,
)
from agentsec.rules.builtin import (
    BUILTIN_MARKDOWN_RULE_COUNT,
    BUILTIN_MARKDOWN_RULE_IDS,
    builtin_markdown_rules,
)
from agentsec.rules.matching import (
    MAX_CANDIDATES_PER_RULE,
    MAX_CONTEXT_WINDOW_LINES,
    MAX_EVIDENCE_EXCERPT_CHARACTERS,
    MAX_KEYWORD_CHARACTERS,
    MAX_KEYWORD_LINE_CHARACTERS,
    MAX_KEYWORDS_PER_CONDITION,
    MAX_REGEX_LINE_CHARACTERS,
    MAX_REGEX_PATTERN_CHARACTERS,
    MAX_REGEX_PATTERNS_PER_CONDITION,
    ContextWindow,
    KeywordCondition,
    KeywordRule,
    MatchMode,
    RegexCondition,
    RegexRule,
)
from agentsec.rules.pipeline import (
    DeterministicRuleRunner,
    RuleFailure,
    RulePipelineError,
    RuleRegistryError,
    RuleRunResult,
    UnscoredFinding,
    merge_rule_coverage,
)

__all__ = [
    "BUILTIN_MARKDOWN_RULE_COUNT",
    "BUILTIN_MARKDOWN_RULE_IDS",
    "builtin_markdown_rules",
    "DeterministicRuleRunner",
    "RuleFailure",
    "RulePipelineError",
    "RuleRegistryError",
    "RuleRunResult",
    "UnscoredFinding",
    "merge_rule_coverage",
    "MAX_CANDIDATES_PER_RULE",
    "MAX_CONTEXT_WINDOW_LINES",
    "MAX_EVIDENCE_EXCERPT_CHARACTERS",
    "MAX_KEYWORD_CHARACTERS",
    "MAX_KEYWORD_LINE_CHARACTERS",
    "MAX_KEYWORDS_PER_CONDITION",
    "MAX_REGEX_LINE_CHARACTERS",
    "MAX_REGEX_PATTERN_CHARACTERS",
    "MAX_REGEX_PATTERNS_PER_CONDITION",
    "ContextWindow",
    "KeywordCondition",
    "KeywordRule",
    "MatchMode",
    "RegexCondition",
    "RegexRule",
    "Rule",
    "RuleContext",
    "RuleContractError",
    "RuleEvaluation",
    "RuleEvaluationError",
    "RuleEvidenceCandidate",
    "RuleFindingCandidate",
    "RuleMetadata",
    "RuleScope",
    "RuleTarget",
]
